"""add section_id to student_profiles

Revision ID: 89925725802a
Revises: 0c48d27e08f4
Create Date: 2026-03-24 22:34:44.275669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89925725802a'
down_revision: Union[str, Sequence[str], None] = '0c48d27e08f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'course_id')
    )
    op.add_column('sections', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('sections', sa.Column('guide_professor_id', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('specialty_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('sections_course_id_fkey'), 'sections', type_='foreignkey')
    op.drop_constraint(op.f('sections_professor_id_fkey'), 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'specialties', ['specialty_id'], ['id'])
    op.create_foreign_key(None, 'sections', 'users', ['guide_professor_id'], ['id'])
    op.drop_column('sections', 'professor_id')
    op.drop_column('sections', 'shift')
    op.drop_column('sections', 'course_id')
    op.add_column('student_profiles', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_profiles', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'section_id')
    op.add_column('sections', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sections', sa.Column('shift', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sections', sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.create_foreign_key(op.f('sections_professor_id_fkey'), 'sections', 'users', ['professor_id'], ['id'])
    op.create_foreign_key(op.f('sections_course_id_fkey'), 'sections', 'courses', ['course_id'], ['id'])
    op.drop_column('sections', 'specialty_id')
    op.drop_column('sections', 'guide_professor_id')
    op.drop_column('sections', 'name')
    op.drop_table('section_courses')
    # ### end Alembic commands ###
