"""drop specialty_id from sections

Revision ID: 900e8d42ddd8
Revises: 89925725802a
Create Date: 2026-03-25 00:07:47.940554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900e8d42ddd8'
down_revision: Union[str, Sequence[str], None] = '89925725802a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_specialties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('part', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('sections_specialty_id_fkey'), 'sections', type_='foreignkey')
    op.drop_column('sections', 'specialty_id')
    op.add_column('student_profiles', sa.Column('section_part', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'section_part')
    op.add_column('sections', sa.Column('specialty_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sections_specialty_id_fkey'), 'sections', 'specialties', ['specialty_id'], ['id'])
    op.drop_table('section_specialties')
    # ### end Alembic commands ###
