"""a

Revision ID: f97d4b17bd2e
Revises: 4d793ac4699e
Create Date: 2026-04-02 03:23:16.175009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97d4b17bd2e'
down_revision: Union[str, Sequence[str], None] = '4d793ac4699e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'enrollments', ['user_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='unique')
    # ### end Alembic commands ###
